FROM nginx
COPY nginx.conf.prod /etc/nginx/nginx.conf
COPY dist /usr/share/nginx/html

COPY ./ssl/fullchain.crt /usr/ssl/pub/fullchain.crt
COPY ./ssl/private.key /usr/ssl/priv/private.key
COPY ./ssl/priv-key-pwd.txt /usr/ssl/priv/priv-key-pwd.txt

RUN chmod 644 /usr/ssl/pub/*.crt \
  && chmod 640 /usr/ssl/priv/*.key \
  && chmod 640 /usr/ssl/priv/*.txt


